version: 2
jobs:
  build:
    machine: true
    steps:
      # Prepare
      - checkout
      - run:
          name: Update Docker
          command: curl https://get.docker.com | sh

      # Build
      - run:
          name: Build Docker image
          command: docker build -t pwned-passwords .

      # Test
      - run:
          name: Fake pwned passwords
          command: |
            echo 'F0D4031B7FBA0204D7DFF0D63198FA9369AE7073' > pwned-passwords-1.0.txt
            touch pwned-passwords-update-1.txt
            echo "pwned-passwords-update-2.txt will be downloaded by container"
      - run:
          name: Test Docker image
          command: docker run -v $(pwd):/data pwned-passwords CirclePassword | grep -c "Oh no"
      - run:
          name: Test Docker image
          command: docker run -v $(pwd):/data pwned-passwords PasswordNotFound

      # Deploy
      - deploy:
          name: Deploy Docker image
          command: |
            export TAG=$(git describe --exact-match $CIRCLE_SHA1 2>/dev/null)
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker tag pwned-passwords stefanscherer/pwned-passwords
              docker push stefanscherer/pwned-passwords
            fi
