version: 2
jobs:
  build:
    machine: true
    steps:
      # Prepare
      - checkout

      # Build
      - run:
          name: Build Docker image
          command: docker build -t pwned-passwords .

      # Test
      - run:
          name: Test Docker image
          command: ./test.sh

      # Deploy
      - deploy:
          name: Deploy Docker image
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker tag pwned-passwords stefanscherer/pwned-passwords:$CIRCLE_TAG
              docker push stefanscherer/pwned-passwords:$CIRCLE_TAG
              docker tag pwned-passwords stefanscherer/pwned-passwords
              docker push stefanscherer/pwned-passwords
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
