version: 2
jobs:
  build:
    machine: true
    steps:
      # Prepare
      - checkout
      - run:
          name: Update Docker
          command: curl https://get.docker.com | sh

      # Build
      - run:
          name: Build Docker image
          command: docker build -t pwned-passwords .

      # Test
      - run:
          name: Test Docker image
          command: ./test.sh

      # Deploy
      - deploy:
          name: Deploy Docker image
          command: |
            export TAG=$(git describe --exact-match $CIRCLE_SHA1 2>/dev/null)
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker tag pwned-passwords stefanscherer/pwned-passwords
              docker push stefanscherer/pwned-passwords
            fi
